### ISSUE TITLE
RALibRetro Clone Achievement crashes program

### ISSUE THREAD

**Issue by grenade44** [leiradel/RASuite#24] opened 2018-03-02 19:35 UTC
I tried cloning a achievement I made in the atari 2600 core and it just crashes the whole program.

**Comment by leiradel** [comment] 2018-03-02 20:16
I take it only happens with the Atari 2600 core right?

**Comment by grenade44** [comment] 2018-03-02 22:36
just tested with handy and that works fine

**Comment by meleu** [comment] 2018-03-05 21:14
Unable to reproduce here. I used the "Clone Selected" button several times when working on my Atari 2600 sets and it works just fine.

**Comment by leiradel** [comment] 2018-03-05 21:24
@meleu Thanks for your help.

@grenade44 I'm closing this issue. If it happens again, please reopen it and add the steps necessary to reproduce it.

**Closed by leiradel** 2018-03-05 21:24 UTC
Labels: bug, help wanted

**Comment by grenade44** [comment] 2018-03-05 21:49
Just downloaded latest build and works fine for me now.

**Comment by leiradel** [comment] 2018-03-05 21:50
Great, thanks for the report.
