### ISSUE TITLE
Adding a bookmark freeze the memory inspector

### ISSUE THREAD

**Issue by Altomar79** [leiradel/RASuite#15] opened 2018-02-26 02:38 UTC
When you add a bookmark on memory bookmarker the memory inspector stop updating the values or the notes when you scroll them down (Watching) unless you move your mouse over the emulator itself and then again you have to move the mouse constantly to keep refreshing the values. If you remove every bookmark then the memory inspector will work again without any problem.

I was playing with master system (tested both cores).

**Comment by leiradel** [comment] 2018-02-26 21:30
@Altomar79 can you please confirm that this issue doesn't happen with the official emulators? Thanks.

**Comment by Altomar79** [comment] 2018-02-26 21:49
I confirm.  I tried on RAVisualBoyAdvance , RAP64 and RASnes9x  and they seems to work fine without any problem. This issue appear only on RaLibretro when you add a bookmark. If you remove all bookmarks or just close the memory bookmarker everything work again fine

**Comment by meleu** [comment] 2018-02-27 01:05
@leiradel I confirm this issue and here is a video showing it:
https://youtu.be/N6BxZdvTIMY

**Comment by leiradel** [comment] 2018-02-27 09:34
Thanks people. You've used RALibretro's `RA_Integration.dll` in the tests, correct?

**Comment by meleu** [comment] 2018-02-27 11:56
@leiradel yes, I'm using the version that @GameDragon2k built yesterday (26-Feb-2018) and @JuliaWolska uploaded to her pack (the same we link on our [Downloads page](https://retroachievements.github.io/docs/Downloads/)).

**Comment by Altomar79** [comment] 2018-02-27 16:05
Yes , i used the same link too. I think the last one i used was the one were you fixed the hardcore crush issue when no rom is loaded. 1.0.180227

**Comment by GameDragon2k** [comment] 2018-02-27 20:11
This is semi-related, but I also noticed that the bit flags and memory search results do not update fast enough. Maybe about every second or so.

My first guess is that it means DoAchievementFrame isn't being called enough.

As for this issue, I ran into this with PJ64 emulator as well. The problem was that DoAchievementFrame was being called from the message loop. I ended up moving it to the rendering loop. Not exactly sure if it's the same problem here.

**Comment by leiradel** [comment] 2018-02-28 09:37
I'm calling `RA_DoAchievementsFrame` once for every emulated core frame: https://github.com/leiradel/RASuite/blob/master/RALibretro/src/Application.cpp#L304

Maybe I need to call it at least once per frame, i.e. even if the game is paused?

**Comment by GameDragon2k** [comment] 2018-02-28 09:52
Nah, once per emulated frame should be accurate.

**Comment by leiradel** [comment] 2018-02-28 10:05
> As for this issue, I ran into this with PJ64 emulator as well. The problem was that DoAchievementFrame was being called from the message loop. I ended up moving it to the rendering loop. Not exactly sure if it's the same problem here.

Can you elaborate? Do those loops run in different threads? In RALibretro, the message loop empties the event queue, runs the necessary core frames, and then renders the video, all in the same thread.

Rendering the video does block the message loop since I wait for the vsync, maybe this is the source of the issue?

**Comment by GameDragon2k** [comment] 2018-02-28 10:22
The rendering loop in PJ64 is indeed on a separate thread, so that solution probably isn't helpful.

The fact that things start updating correctly while the mouse is moving like @Altomar79 said makes me think the issue is with the message loop.

**Comment by Jamiras** [comment] 2018-03-18 20:39
There definitely seems to be something up with the message loops. If several custom message loops are in play at the same time, it seems like only one is actively processing messages. For example, I noticed that invalidating both the search results control and the memory viewer control would only repaint one or the other, but magically both would be called if the mouse was moved over the MAIN window. I added explicit UpdateWindow calls to address this until I can further investigate. 

I've posted a temporary DLL to the ralibretro discord channel while I continue working. I believe it addresses everything in this issue, and cleans up the flickering in the tool windows mentioned in #20.

This only happens in RALibRetro, so there's got to be something it's doing that's unique. I'm hoping I find something when looking into the overlay flickering issues.

**Comment by Jamiras** [comment] 2018-03-19 01:52
I've posted a new DLL to the ralibretro discord channel that addresses this and #20 as best as is possible without major changes to the overlay implementation (more details in #20). The forced UpdateWindow calls are still present. I was unable to determine why they were necessary. I suspect is has something to do with the SDL.

I'm going to run with the changes for a few days before opening a PR. If you're interested in the changes, see https://github.com/Jamiras/RASuite/compare/master...dlg_flicker?expand=1

**Comment by leiradel** [comment] 2018-03-21 21:44
Is this solved with the latest integration DLL?

**Comment by Altomar79** [comment] 2018-03-21 22:06
Sorry for the delay. Yes, it work fine while memory bookmarker is open.
Thanks for the fix

**Comment by leiradel** [comment] 2018-03-21 22:12
Thanks

**Closed by leiradel** 2018-03-21 22:12 UTC
Labels: bug
